name: shubham_practical
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6

  # Screen Utils
  flutter_screenutil: ^5.9.3

  # Fonts Style
  google_fonts: ^6.2.1

  # Dio
  dio: ^5.6.0

  #Dio Logger
  pretty_dio_logger: ^1.4.0

  #Connectivity
  connectivity_plus: ^4.0.2

  #Shared Preference
  shared_preferences: ^2.2.0

  # Cache Network Image
  cached_network_image: ^3.3.0

  #Dotted Border
  dotted_border: ^2.0.0+3

  #Image Picker
  image_picker: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


